### ISSUE TITLE
when does the error 'no utterance found' arrises ? can you please explain it.

### ISSUE THREAD

**Issue by DanishBaloch010** [ludlows/PESQ#43]
i am trying to measure objective score on my dataset. but this is throwing me this error. even though with the same settings i have calculated pesq on a subset of my data.

**Comment by ludlows** [comment]
`no utterance found` is raised when the program cannot detect a speech signal.

**Comment by JCCC0328** [comment]
> i am trying to measure objective score on my dataset. but this is throwing me this error. even though with the same settings i have calculated pesq on a subset of my data.

Hi, Did you solve the problem ？ I had this problem when testing my own data and it was with a speech signal.

**Comment by Sreyan88** [comment]
Same, is this problem solved?

**Comment by ludlows** [comment]
@Sreyan88 could you upload the sample for us to test?

**Comment by wuhongsheng** [comment]
+1  data is all 0
