### ISSUE TITLE
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

### ISSUE THREAD

**Issue by Tienyaul** [ludlows/PESQ#44]
I got this Error, what should I do for it? 
Thx for helping or any way might solve it.
![image](https://user-images.githubusercontent.com/71646293/220033721-b54a11ea-bbbd-4d37-8698-b43ad8d2c041.png)

**Comment by ludlows** [comment]
function `pesq` takes 1-D numpy arrays as the inputs.

**Comment by Tienyaul** [comment]
O~ Thanks for answer. 
So as next step, I need to transfer WAV file to be single track that get 1-D numpy arrays. 
Am I right? Or is there any easier way just read the audio file be 1-D numpy arrays?

**Comment by ludlows** [comment]
Hi @Tienyaul ,

in the [readme.md](https://github.com/ludlows/PESQ/blob/master/README.md), we have an example showing you to load wav files in the numpy format. 

```python
from scipy.io import wavfile
from pesq import pesq

rate, ref = wavfile.read("./audio/speech.wav")
rate, deg = wavfile.read("./audio/speech_bab_0dB.wav")
````
