### ISSUE TITLE
What's the difference between pypesq and pesq?  What is the difference between the output values of the different options 'wb' and 'nb'

### ISSUE THREAD

**Issue by fff-wang** [ludlows/PESQ#47]
There is another Python implementation library of PESQ called "pypesq". However, when I use "pypesq" and the PESQ library with the 'nb' option to calculate PESQ scores for the same pair of 16 kHz audio, there are differences in the output results. For example, "pypesq" outputs 2.26, while "PESQ" with the 'nb' option outputs 2.05 and with the 'wb' option outputs 2.13. What does the difference in values between "pypesq" and "PESQ" with the 'nb' option imply? And what does the different outputs between the 'nb' and 'wb' options indicate?

I am currently exploring the field of speech enhancement, but I found that many articles do not specifically mention their methods for calculating PESQ scores. Some articles report high PESQ scores while others report low ones, apparently related to the mode option used. So, which option should I use when calculating PESQ scores for 16 kHz audio?

I look forward to someone responding. Thank you very much.

**Comment by ludlows** [comment]
hi, I am not familiar with `pypesq` code. for the current `PESQ` you could refere to this issue.https://github.com/ludlows/PESQ/issues/13

**Comment by canon1111k** [comment]
> There is another Python implementation library of PESQ called "pypesq". However, when I use "pypesq" and the PESQ library with the 'nb' option to calculate PESQ scores for the same pair of 16 kHz audio, there are differences in the output results. For example, "pypesq" outputs 2.26, while "PESQ" with the 'nb' option outputs 2.05 and with the 'wb' option outputs 2.13. What does the difference in values between "pypesq" and "PESQ" with the 'nb' option imply? And what does the different outputs between the 'nb' and 'wb' options indicate?
> 
> I am currently exploring the field of speech enhancement, but I found that many articles do not specifically mention their methods for calculating PESQ scores. Some articles report high PESQ scores while others report low ones, apparently related to the mode option used. So, which option should I use when calculating PESQ scores for 16 kHz audio?
> 
> I look forward to someone responding. Thank you very much.
Hello, I also encountered a similar problem, can I communicate with you, my email is 1240707003@qq.com
