### ISSUE TITLE
PESQ score greater than 4.5?

### ISSUE THREAD

**Issue by frankfyf** [ludlows/PESQ#51]
It has been mentioned in many literature that the PESQ score should be ranged from -0.5 to 4.5, but when I set the ref and the deg to be the same it always return a constant value greater than 4.5 (~4.64 actually) , is this something by design or did I missed anything? 

For example:
```
fs = 16000
duration = 10
rand_audio = np.random.randn(duration*fs)
pesq(
    fs,
    rand_audio,
    rand_audio,
    'wb'
)
```
always gives
`4.643888473510742`

**Comment by ludlows** [comment]
Hi @frankfyf ,
have you check this issue (https://github.com/ludlows/PESQ/issues/13)?
