### ISSUE TITLE
pip install pesq 出现的问题

### ISSUE THREAD

**Issue by a897456** [ludlows/PESQ#52]
![image](https://github.com/ludlows/PESQ/assets/28752526/42f8cbfc-04e8-4349-a072-3e0a7263fc16)
请问这是什么问题？全网也找不到类似的解决方案

**Comment by ludlows** [comment]
please try to install 'microsoft visual c++ 14.0 or greater'. you can get it with microsoft c++ build tools.

**Comment by a897456** [comment]
你有没有发现项目下的pesq文件夹和pesq模型，由于命名相同，在引用过程中，有点乱套？
