### ISSUE TITLE
vaule more than 4.5

### ISSUE THREAD

**Issue by crazyrayLing** [ludlows/PESQ#53]
i test the model you design for two same wav files, but the vaule is more than 4.5,how to  explain it!
![1702711752866](https://github.com/ludlows/PESQ/assets/62822498/14ed12ac-897c-4248-87df-0a4085b9ada6)

**Comment by Shetu1994** [comment]
I also found it.

**Comment by ludlows** [comment]
hi guys, 
 please check this issue https://github.com/ludlows/PESQ/issues/13
